version: 2
jobs:
  deploy:
    docker: 
      - image: circleci/python

    steps:
      - checkout

      - setup_remote_docker:
          docker_layer_caching: true

      - run:
          name: Login to docker hub
          command: docker login -u $DOCKER_USER -p $DOCKER_PASS

      - run:
          name: Build image
          command: docker build -t shwanton/circleci .

      - deploy:
          name: Push image
          command: docker push shwanton/circleci

workflows:
  version: 2
  deploy_docker_hub:
    jobs:
      - deploy:
          context: org-global  
